### ISSUE TITLE
Lack of chart and background

### ISSUE THREAD

**Issue by JuanpivrouwuIsASigma** [JordanSantiagoYT/FNF-JS-Engine#743] opened 2024-11-15 19:45 UTC
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

Its the actual, fresh and new Engine, i've been using it for a while now, but I never seen a thing like this:

https://github.com/user-attachments/assets/65f46b0d-0c88-4ed7-8034-69167bde656d

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

playing the literal game (happens on all songs)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

*

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment] 2024-11-15 20:16
I have already identified this issue, and 1.38.1 will come out soon fixing this bug.

**Comment by StinkTheStinker** [comment] 2024-11-15 22:54
what the fuck

**Comment by JordanSantiagoYT** [comment] 2024-11-15 23:21
background issue is either due to low memory usage or the update not installing correctly

**Comment by JordanSantiagoYT** [comment] 2024-11-15 23:51
also partially a duplicate of #744

**Comment by JordanSantiagoYT** [comment] 2024-11-16 06:49
Closed by the most recent release.

**Closed by JordanSantiagoYT** 2024-11-16 06:49 UTC
Labels: bug, partial duplicate
