### ISSUE TITLE
Crashing whenever I try to play a song

### ISSUE THREAD

**Issue by ISamwise4** [JordanSantiagoYT/FNF-JS-Engine#650] opened 2024-10-14 01:14 UTC
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

I- I just can't play any song, what is happening

### Command Prompt/Terminal/Crash logs (if existing)

Uncaught Error: Null Object Reference
flixel/animation/FlxAnimationController.findByPrefix() [line 739]
Paths.addAnimAndCheck() [line 156]
Paths.initSplash() [line 138]
NoteSplash.loadAnims() [line 116]
NoteSplash.setupNoteSplash() [line 63]
NoteSplash.new() [line 44]
PlayState.create() [line 1190]
flixel/FlxGame.switchState() [line 639]
flixel/FlxGame.update() [line 726]
flixel/FlxGame.step() [line 679]
flixel/FlxGame.onEnterFrame() [line 558]
openfl/events/EventDispatcher.__dispatchEvent() [line 426]
openfl/display/DisplayObject.__dispatch() [line 1398]
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-JS-Engine
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't delete anything

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by StinkTheStinker** [comment] 2024-10-14 02:18
did you play only one song or more?

**Comment by ISamwise4** [comment] 2024-10-14 02:21
> did you play only one song or more?

**Comment by StinkTheStinker** [comment] 2024-10-14 02:21
what

**Comment by ISamwise4** [comment] 2024-10-14 02:21
It crashes on every song

**Comment by ISamwise4** [comment] 2024-10-14 02:22
ill send a video

**Comment by ISamwise4** [comment] 2024-10-14 02:23
https://github.com/user-attachments/assets/b2c2d5d4-d374-40f6-bfcc-24dbc6326ca8

**Comment by StinkTheStinker** [comment] 2024-10-14 02:26
alright
open cmd and do "cd [path of where the '.exe' is]"
and then type in "JSEngine.exe"
this shows what event is going on in the engine
go to a song and watch the terminal
![image](https://github.com/user-attachments/assets/e54456e9-c4c1-48ba-988d-95221780ac30)

**Comment by StinkTheStinker** [comment] 2024-10-14 02:27
also, click on "comment", not "close commit" (or whatever that button says)

**Comment by StinkTheStinker** [comment] 2024-10-14 02:32
heres a video just so its easier to understand

https://github.com/user-attachments/assets/c8b640b0-e386-4195-b5aa-8c009c425f3d

if you dont know how to open cmd, go to the search and type cmd

**Comment by StinkTheStinker** [comment] 2024-10-14 02:40
copy the section that looks like its talking about the crash

**Comment by ISamwise4** [comment] 2024-10-14 02:42
it opens JSEngine, and that's it, it literally doesn't give me other info

**Comment by StinkTheStinker** [comment] 2024-10-14 02:43
is there litteraly nothing in the cmd post-opening the the game with cmd

**Comment by ISamwise4** [comment] 2024-10-14 02:47
https://github.com/user-attachments/assets/2aee82fa-7871-4225-a49b-70221da37751

**Comment by ISamwise4** [comment] 2024-10-14 02:48
🤷

**Comment by StinkTheStinker** [comment] 2024-10-14 02:50
without the quotation marks

**Comment by ISamwise4** [comment] 2024-10-14 02:52
https://github.com/user-attachments/assets/8eefdcfb-b24f-45ea-a3be-de6f6325d074

**Comment by StinkTheStinker** [comment] 2024-10-14 02:53
no
see that path thing next to the search bar on the file explorer

**Comment by StinkTheStinker** [comment] 2024-10-14 02:54
nvm
just get rid of  "\JSEngine.exe"  and keep the rest
then type in JSEngine.exe

**Comment by ISamwise4** [comment] 2024-10-14 02:57
im an idiot

https://github.com/user-attachments/assets/3cbf826f-82fb-4f5e-99c3-c737afc39763

**Comment by StinkTheStinker** [comment] 2024-10-14 02:58
send me the directory you are typing in

**Comment by ISamwise4** [comment] 2024-10-14 02:59
I'm generally new to Windows, I got this pc less that a month ago and I don't know wtf I'm doing

**Comment by StinkTheStinker** [comment] 2024-10-14 03:00
send the directory

**Comment by ISamwise4** [comment] 2024-10-14 03:00
"C:\Users\[MY NAME]\Desktop\fnf-stuff\FNF-JS-Engine-windows" is the directory, it is where JSEngine is saved

**Comment by StinkTheStinker** [comment] 2024-10-14 03:00
`cd C:\Users[MY NAME]\Desktop\fnf-stuff\FNF-JS-Engine-windows`

**Comment by StinkTheStinker** [comment] 2024-10-14 03:01
you forgot the cd at the start

**Comment by JordanSantiagoYT** [comment] 2024-10-14 03:02
ok

first of all, you're cding to "C:\Users[MY NAME]\Desktop\fnf-stuff\FNF-JS-Engine-windows\JSEngine.exe"

while the file is existent, that doesnt mean its an existent directory. you should try "C:\Users[MY NAME]\Desktop\fnf-stuff\FNF-JS-Engine-windows" only

second, the issue you're reporting is yet another duplicate of https://github.com/JordanSantiagoYT/FNF-JS-Engine/issues/559, also be sure to see https://github.com/JordanSantiagoYT/FNF-JS-Engine/issues/359 and https://github.com/JordanSantiagoYT/FNF-JS-Engine/issues/576

**Comment by ISamwise4** [comment] 2024-10-14 03:03
https://github.com/user-attachments/assets/89a1c847-9c3a-4f80-9025-896a6288b1ec

**Closed** 2024-10-14 03:02 UTC
Labels: bug

**Comment by StinkTheStinker** [comment] 2024-10-14 03:04
note splash directory is incorrect

**Comment by JordanSantiagoYT** [comment] 2024-10-14 03:04
since you're trying on 1.32.0/newer, go to Options, enter the Visuals & UI menu to reset your note splash/skin settings to defaults, then try again. 

If it still crashes, then you're missing a required config file for your game to work. Head to the Note Splash Editor by pressing 7 in the main menu, then entering the Note Splash Debug Editor and create one for your skin.

**Comment by ISamwise4** [comment] 2024-10-14 03:05
Ok, thanks
