### ISSUE TITLE
I just compiled JSE 1.35 and i'm already having an error with it.

### ISSUE THREAD

**Issue by ARandomGuylol** [JordanSantiagoYT/FNF-JS-Engine#648] opened 2024-10-11 20:56 UTC
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

it's somewhat clean, i just moved my assets into the newer JSE directory.

### Command Prompt/Terminal/Crash logs (if existing)

Uncaught Error: Null Object Reference
flixel/animation/FlxAnimationController.findByPrefix() [line 739]
Paths.addAnimAndCheck() [line 156]
Paths.initSplash() [line 138]
NoteSplash.loadAnims() [line 116]
NoteSplash.setupNoteSplash() [line 63]
NoteSplash.new() [line 44]
PlayState.create() [line 1190]
flixel/FlxGame.switchState() [line 639]
flixel/FlxGame.update() [line 726]
flixel/FlxGame.step() [line 679]
flixel/FlxGame.onEnterFrame() [line 558]
openfl/events/EventDispatcher.__dispatchEvent() [line 426]
openfl/display/DisplayObject.__dispatch() [line 1398]

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

No, not at all. The only thing i did was just compile the engine.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

At first, no.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by JordanSantiagoYT** [comment] 2024-10-11 21:36
duplicate of #559 + see #359 and #576

**Closed by JordanSantiagoYT** 2024-10-11 21:36 UTC
Labels: bug
