### ISSUE TITLE
keeps crashing whenever i open a song

### ISSUE THREAD

**Issue by sw97awesome** [JordanSantiagoYT/FNF-JS-Engine#813] opened 2024-12-19 22:36 UTC
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

When I try to open any song, it crashes and gives me this error. I have updated to the Latest Version of JSE (1.39.1), I even tried redownloading the file and it still gives me the error. There is nothing in my mod folder and nothing in the files have been changed. 

### Command Prompt/Terminal/Crash logs (if existing)

[JSEngine_2024-12-19_17'32'23.log](https://github.com/user-attachments/files/18203816/JSEngine_2024-12-19_17.32.23.log)
[JSEngine_2024-12-19_17'30'59.log](https://github.com/user-attachments/files/18203817/JSEngine_2024-12-19_17.30.59.log)
[JSEngine_2024-12-19_17'29'31.log](https://github.com/user-attachments/files/18203818/JSEngine_2024-12-19_17.29.31.log)

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

https://github.com/user-attachments/assets/12d37a96-f8a8-4244-92a6-1d83f0efe656

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I did not edit anything

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by StinkTheStinker** [comment] 2024-12-19 23:28
go to the debug menu and go to note splash debug.
its a note splash issue

**Comment by JordanSantiagoYT** [comment] 2024-12-20 02:23
Duplicate of #559

For more info to fix: https://github.com/JordanSantiagoYT/FNF-JS-Engine/issues/774#issuecomment-2509425975

**Comment by JordanSantiagoYT** [comment] 2024-12-20 02:23
ive said this type of issue was a duplicate so many times that even i'm starting to copy paste others' comments saying that this is a duplicate

**Closed** 2024-12-20 09:09 UTC
Labels: bug
