### ISSUE TITLE
js engine not updating to 1.37.1

### ISSUE THREAD

**Issue by stripes10122** [JordanSantiagoYT/FNF-JS-Engine#722] opened 2024-11-03 15:44 UTC
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

its not updating, i press hte update and it opens js engine zgai biut its not in the latest

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

update it

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by JordanSantiagoYT** [comment] 2024-11-03 16:25
Duplicate of #718.

It's possible that because of your device, the game doesn't close quickly enough for CMD to detect that JSE is closed, and the EXE isn't replaced as a result.

The only fix for this would be to download the update off GitHub and install it manually.

**Comment by stripes10122** [comment] 2024-11-03 23:27
ok

**Comment by StinkTheStinker** [comment] 2024-11-04 03:40
close?

**Closed** 2024-11-04 03:42 UTC
Labels: bug, duplicate
