### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by stripes10122** [JordanSantiagoYT/FNF-JS-Engine#700] opened 2024-10-28 19:38 UTC
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

latest edition

i pressed ctrl z adn it crashed, whats happening

### Command Prompt/Terminal/Crash logs (if existing)

Uncaught Error: Null Object Reference
editors/ChartingState.update() [line 3042]
flixel/FlxState.tryUpdate() [line 239]
flixel/FlxGame.update() [line 749]
flixel/FlxGame.step() [line 679]
flixel/FlxGame.onEnterFrame() [line 558]
openfl/events/EventDispatcher.__dispatchEvent() [line 426]
openfl/display/DisplayObject.__dispatch() [line 1398]
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-JS-Engine
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

press xontrol z after makign some spam

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

Yes

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by StinkTheStinker** [comment] 2024-10-28 19:44
open cmd promnt and type in "cd [your directory where it leads to the exe file, without the .exe]", then tell me what it says before crashing

**Comment by JordanSantiagoYT** [comment] 2024-10-28 19:49
This is a duplicate of #670, and has already been fixed.

**Closed by JordanSantiagoYT** 2024-10-28 19:49 UTC
Labels: bug

**Comment by stripes10122** [comment] 2024-10-28 22:47
The system cannot find the path specified.

**Comment by moxie-coder** [comment] 2024-10-28 23:37
it’s a duplicate of an already fixed issue
