### ISSUE TITLE
Placing Note Crash

### ISSUE THREAD

**Issue by AlienCat65** [JordanSantiagoYT/FNF-JS-Engine#556] opened 2024-09-08 19:57 UTC
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

this happens randomly for some reaason, and its getting pretty annoying

### Command Prompt/Terminal/Crash logs (if existing)

```bash
Uncaught Error: Null Object Reference
Note.updateRGBColors() [line 536]
editors/ChartingState.addNote() [line 4036]
editors/ChartingState.update() [line 2551]
flixel/FlxState.tryUpdate() [line 239]
flixel/FlxGame.update() [line 749]
flixel/FlxGame.step() [line 679]
flixel/FlxGame.onEnterFrame() [line 558]
openfl/events/EventDispatcher.__dispatchEvent() [line 426]
openfl/display/DisplayObject.__dispatch() [line 1398]
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-JS-Engine
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!
```

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

```bash
opening chart editor
and placing note
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Not really, just copied scripts from nusm (credited btw)

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by AlienCat65** [comment] 2024-09-08 19:59
forgot to add it, theres no similar issues just that one

**Comment by AlienCat65** [comment] 2024-09-08 19:59
mb i didnt know what that was

**Comment by JordanSantiagoYT** [comment] 2024-09-08 21:31
duplicate of #555

**Comment by JordanSantiagoYT** [comment] 2024-09-08 21:31
also already fixed in latest commit

**Closed by JordanSantiagoYT** 2024-09-08 21:31 UTC
Labels: bug
