### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by mihaillov** [JordanSantiagoYT/FNF-JS-Engine#674] opened 2024-10-20 09:55 UTC
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

I migrated my mod from 1.31.0 to 1.36.0 and when i enter to the songs and game crashes with this error

### Command Prompt/Terminal/Crash logs (if existing)

Uncaught Error: Null Object Reference
flixel/animation/FlxAnimationController.findByPrefix() [line 739]
Paths.addAnimAndCheck() [line 156]
Paths.initSplash() [line 138]
NoteSplash.loadAnims() [line 116]
NoteSplash.setupNoteSplash() [line 63]
NoteSplash.new() [line 44]
PlayState.create() [line 1182]
flixel/FlxGame.switchState() [line 639]
flixel/FlxGame.update() [line 726]
flixel/FlxGame.step() [line 679]
flixel/FlxGame.onEnterFrame() [line 558]
openfl/events/EventDispatcher.__dispatchEvent() [line 426]
openfl/display/DisplayObject.__dispatch() [line 1398]
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-JS-Engine
The engine has saved a crash log inside the crash folder, If you're making a GitHub issue you might want to send that!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by mihaillov** [comment] 2024-10-20 10:12
Also i cant enter to Tutorial

**Comment by mihaillov** [comment] 2024-10-20 10:13
this error also appears on Vanilla version of JS Engine

**Comment by mihaillov** [comment] 2024-10-20 10:43
> this error also appears on Vanilla version of JS Engine

without mods

**Comment by PatoFlamejanteTV** [comment] 2024-10-20 13:05
Try re-installing the JS-Engine

**Comment by JordanSantiagoYT** [comment] 2024-10-20 16:43
duplicate of #559.

try going to Options, enter the Visuals & UI menu to reset your note splash/skin settings to defaults, then try again. If it still crashes, then you're missing a required config file for your game to work. Head to the Note Splash Editor by pressing 7 in the main menu, then entering the Note Splash Debug Editor and create one for your skin.

**Closed** 2024-10-20 17:22 UTC
Labels: bug, duplicate, impact: medium

**Comment by mihaillov** [comment] 2024-10-20 20:29
thanks i will try this later
