### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by jogsg** [JordanSantiagoYT/FNF-JS-Engine#621] opened 2024-09-28 11:46 UTC
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

i was trying to play a level and this happens "Uncaught Error: Null Object Reference
Paths.initSplash() [line 128]
NoteSplash.loadAnims() [line 116]
NoteSplash.setupNoteSplash() [line 63]
NoteSplash.new() [line 44]
PlayState.create() [line 1205]
flixel/FlxGame.switchState() [line 639]
flixel/FlxGame.update() [line 726]
flixel/FlxGame.step() [line 679]
flixel/FlxGame.onEnterFrame() [line 558]
openfl/events/EventDispatcher.__dispatchEvent() [line 426]
openfl/display/DisplayObject.__dispatch() [line 1398]
Please report this error to the GitHub page: https://github.com/JordanSantiagoYT/FNF-JS-Engine

" i dont know what does it mean can you fix it

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JordanSantiagoYT** [comment] 2024-09-28 11:47
1. wrong issue template
2. duplicate of #559 + see #359

**Closed by JordanSantiagoYT** 2024-09-28 11:47 UTC
Labels: help wanted
