### ISSUE TITLE
JSE wont update

### ISSUE THREAD

**Issue by JuanpivrouwuIsASigma** [JordanSantiagoYT/FNF-JS-Engine#599] opened 2024-09-20 17:28 UTC
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

Trying to update to the current version on JSE and..
[image](https://github.com/user-attachments/assets/51836b2c-303d-4a69-bf0b-04707f71f662)

idk why it happens but I waited here 20 MINUTES, reseted 2 times

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nope, not even making a mod I was thinking of.

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment] 2024-09-20 17:33
duplicate of #600 despite being newer, that help explains it more better

**Closed by moxie-coder** 2024-09-20 17:33 UTC
Labels: bug

**Comment by NAEL2XD** [comment] 2024-09-22 23:43
> duplicate of #600 despite being newer, that help explains it more better 

That's issue #599, not #600 so it isn't a duplicate

**Comment by JordanSantiagoYT** [comment] 2024-09-23 04:58
wait, in that case wouldn't #600 be the duplicate

**Comment by moxie-coder** [comment] 2024-09-23 06:14
> > duplicate of #600 despite being newer, that help explains it more better
> 
> That's issue #599, and it isn't a duplicate. It was made first since you answered to that 600th issue thing

I know that would be the duplicate but it helps explain the issue better
