### ISSUE TITLE
I wanted to play a song but it crashed

### ISSUE THREAD

**Issue by KanbimationsYT** [JordanSantiagoYT/FNF-JS-Engine#719] opened 2024-11-02 22:51 UTC
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

![Screenshot 2024-11-02 154916](https://github.com/user-attachments/assets/8371dabe-1ffd-423d-b867-929f574f0cce)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by KanbimationsYT** [comment] 2024-11-02 22:56
I didn't even get to mod it

**Comment by JordanSantiagoYT** [comment] 2024-11-02 23:23
Duplicate of https://github.com/JordanSantiagoYT/FNF-JS-Engine/issues/559.

try going to Options, enter the Visuals & UI menu to reset your note splash/skin settings to defaults, then try again. If it still crashes, then you're missing a required config file for your game to work. Head to the Note Splash Editor by pressing 7 in the main menu, then entering the Note Splash Debug Editor and create one for your skin.

**Comment by KanbimationsYT** [comment] 2024-11-02 23:33
how do i reset note splash

**Comment by KanbimationsYT** [comment] 2024-11-02 23:35
THANK YOU :D

**Comment by JordanSantiagoYT** [comment] 2024-11-02 23:37
You're welcome :)

**Closed** 2024-11-03 00:08 UTC
Labels: duplicate, help wanted
