### ISSUE TITLE
uhh there is another problem, when I go to play the chart from the "esc" key I get this error.

### ISSUE THREAD

**Issue by CG1396** [JordanSantiagoYT/FNF-JS-Engine#647] opened 2024-10-10 23:51 UTC
### Describe your problem here. If you are modding, please try testing your problem in a clean version of the engine instead, this ensures the problem is actually caused by the engine itself. Also, if you're using an older version of JSE, please try the latest action build in the Actions tab or the latest release build. The issue has probably been fixed since that version. Oh yeah, and also be sure to check the pinned 'JS Engine: Known Issues' issue, to double check if your issue hasn't already been found!

![Captura](https://github.com/user-attachments/assets/8860d7a2-3e46-4edc-a516-f3bf989b5239)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by JordanSantiagoYT** [comment] 2024-10-11 00:01
duplicate of #559, + see #359

**Closed** 2024-10-11 00:04 UTC
Labels: help wanted
