### ISSUE TITLE
what the??

### ISSUE THREAD

**Issue by JvCanWatch5Men** [JordanSantiagoYT/FNF-JS-Engine#797] opened 2024-12-15 01:17 UTC
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

so the mod file that you uploaded on github with some charts basically the songs arent working uhh so

### Command Prompt/Terminal/Crash logs (if existing)

[
![{2BD0EB7E-1AAC-461B-922C-D201EED50BC0}](https://github.com/user-attachments/assets/4f76d59c-e913-4c27-b18f-20b6efee1420)
](url)

### Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

no.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

not really just put everything in mods

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

No

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

No

**Comment by JvCanWatch5Men** [comment] 2024-12-15 01:19
i think there might be a similar issue

**Comment by JordanSantiagoYT** [comment] 2024-12-15 02:58
Duplicate of https://github.com/JordanSantiagoYT/FNF-JS-Engine/issues/559.

try going to Options, enter the Visuals & UI menu to reset your note splash/skin settings to defaults, then try again. If it still crashes, then you're missing a required config file for your game to work. Head to the Note Splash Editor by pressing 7 in the main menu, then entering the Note Splash Debug Editor and create one for your skin.

**Closed** 2024-12-15 05:55 UTC
Labels: bug, duplicate

**Comment by JvCanWatch5Men** [comment] 2024-12-15 13:56
I KNEW IT
