### ISSUE TITLE
Game won't let me play any songs

### ISSUE THREAD

**Issue by SamAlphaTheEpik** [JordanSantiagoYT/FNF-JS-Engine#601] opened 2024-09-20 17:33 UTC
### Describe your bug here. If you are modding, try testing your bug in a clean version of the engine instead. Also, if you're using an older version of JSE, please try the latest version/action build. Also, be sure to check the pinned 'JS Engine: Known Issues' issue, to check if your issue hasn't already been found!

Hello Jordan.

Today i've installed JS engine to make a Sonorous chart but i'm having this problem.
So the game doesn't let me play any of the songs and because of this i can't test my Sonorous chart.
Please do something, thank you.
![Screenshot 2024-09-20 191027](https://github.com/user-attachments/assets/9b4ca986-6918-4d8c-a222-e1eafb2a2a66)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

### If you use 1.12.0 or earlier, did you have Optimized Chart Loading turned on?

None

### Did you check for any similar issues to what you're reporting? Check, then come back here. If there is a similar issue, then do not report the issue, otherwise it will be marked as a duplicate.

Yes

**Comment by moxie-coder** [comment] 2024-09-20 17:35
duplicate of #559 

see #359 btw

**Comment by SamAlphaTheEpik** [comment] 2024-09-20 17:35
Ok thank you.

**Closed by moxie-coder** 2024-09-20 17:35 UTC
Labels: bug

**Comment by SamAlphaTheEpik** [comment] 2024-09-20 17:37
Ok Thank you, Moxie-Coder.

**Comment by moxie-coder** [comment] 2024-09-20 17:38
no problem
